### ISSUE TITLE
When attempting to Open from or Save to Cloud Drive, getting an "Invalid chars in path" exception from the CheckInvalidPathChars() method

### ISSUE THREAD

**Issue by ChaseLukeA** [Kyrodan/KeeAnywhere#125]
Just installed KeeAnywhere for the first time on a Windows 10 Pro machine with current updates. I'm able to successfully add and connect to DropBox, OneDrive, and GoogleDrive via the settings. Any time I try to Open from Cloud Drive or Save to Cloud Drive, I get the following exception. I did run KeePass in debug mode and the error message I receive is the same:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Invalid chars in path.
   at KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   at KeeAnywhere.CloudPath.GetExtension(String path)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.38.0.21288
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
MicrosoftKeyImporterPlugin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/MicrosoftKeyImporterPlugin.DLL
----------------------------------------
CustomIconDashboarderPlugin
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/chase/AppData/Local/KeePass/PluginCache/sS4oUX0oZ3nHr2eOzCGm/CustomIconDashboarderPlugin.dll
----------------------------------------
HaveIBeenPwned
    Assembly Version: 1.2.4.0
    Win32 Version: 1.2.4.0
    CodeBase: file:///C:/Users/chase/AppData/Local/KeePass/PluginCache/mpohhTAusoCqbTUgIh4g/HaveIBeenPwned.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Users/chase/AppData/Local/KeePass/PluginCache/yCF3PAJRJXQzeCVhIILc/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/chase/AppData/Local/KeePass/PluginCache/yCF3PAJRJXQzeCVhIILc/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.2.20802
    CodeBase: file:///C:/Users/chase/AppData/Local/KeePass/PluginCache/yCF3PAJRJXQzeCVhIILc/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Users/chase/AppData/Local/KeePass/PluginCache/yCF3PAJRJXQzeCVhIILc/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
YetAnotherFaviconDownloader
    Assembly Version: 1.1.1.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/Users/chase/AppData/Local/KeePass/PluginCache/J9XWB97Kc0zIXALLZCjS/YetAnotherFaviconDownloader.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.38.0.21288
    Win32 Version: 2.38.0.21288
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
Dropbox.Api
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.6348
    CodeBase: file:///C:/Users/chase/AppData/Local/KeePass/PluginCache/yCF3PAJRJXQzeCVhIILc/Dropbox.Api.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Kyrodan** [comment]
Do you have any uncommon chars in filenames or foldernames in your root folders of your providers? In Goolge Drive for instance it's possible to have a filename which contains double quotes. 
I need the providername and the possible uncommon char.

**Comment by Kyrodan** [comment]
Closing due inactivity.

**Comment by micceo** [comment]
Necro-posting here, but got the same problem with 2.53.1 and Key Anywhere 2.0.3.0

```
************** Exception Text **************
System.ArgumentException: Invalid char in path 'Kopia av Namnlöst formulär
' at position 26: 10 (decimal)
   at KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   at KeeAnywhere.CloudPath.GetExtension(String path)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```
Can't figure out where this "Kopia av Namnlöst formulär" could be that's causing trouble.

And here the rest of the error dump:

```
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.53.1.20815
    Win32 Version: 2.53.1.0
    CodeBase: file:///C:/prg/off/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 2.0.3.0
    Win32 Version: 2.0.3.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.24.0.0
    Win32 Version: 1.24.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Microsoft.Graph.Core.DLL
----------------------------------------
IdentityModel.OidcClient
    Assembly Version: 3.0.0.0
    Win32 Version: 3.1.2.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/IdentityModel.OidcClient.DLL
----------------------------------------
Box.V2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Box.V2.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Google.Apis.Core.DLL
----------------------------------------
CredentialManagement
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/CredentialManagement.DLL
----------------------------------------
IdentityModel
    Assembly Version: 4.1.0.0
    Win32 Version: 4.1.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/IdentityModel.DLL
----------------------------------------
AWSSDK.Core
    Assembly Version: 3.3.0.0
    Win32 Version: 3.5.2.5
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/AWSSDK.Core.DLL
----------------------------------------
AWSSDK.S3
    Assembly Version: 3.3.0.0
    Win32 Version: 3.5.8.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/AWSSDK.S3.DLL
----------------------------------------
Microsoft.Azure.Storage.Common
    Assembly Version: 11.2.2.0
    Win32 Version: 11.2.2.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Microsoft.Azure.Storage.Common.DLL
----------------------------------------
Microsoft.Azure.Storage.Blob
    Assembly Version: 11.2.2.0
    Win32 Version: 11.2.2
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Microsoft.Azure.Storage.Blob.DLL
----------------------------------------
Microsoft.Azure.Storage.File
    Assembly Version: 11.2.2.0
    Win32 Version: 11.2.2
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Microsoft.Azure.Storage.File.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Dropbox.Api
    Assembly Version: 6.6.0.0
    Win32 Version: 6.6.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Dropbox.Api.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.49.0.2201
    Win32 Version: 1.49.0.2201
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Google.Apis.DLL
----------------------------------------
Kyrodan.HiDrive
    Assembly Version: 0.2.0.0
    Win32 Version: 0.2.0.43
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Kyrodan.HiDrive.DLL
----------------------------------------
Microsoft.Graph
    Assembly Version: 3.24.0.0
    Win32 Version: 3.24.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/fDH9qP0NBKKs5yVDt042/Microsoft.Graph.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9110.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
KeePassHttp
    Assembly Version: 2.34.0.0
    Win32 Version: 1.8.4.2
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/IvzuSLRRZarduYZTK4Mj/KeePassHttp.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/IvzuSLRRZarduYZTK4Mj/Newtonsoft.Json.DLL
----------------------------------------
KeePassRPC
    Assembly Version: 2.0.34.24831
    Win32 Version: 1.14.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/ablwE9eTT6KMhu2L7xgG/KeePassRPC.dll
----------------------------------------
Jayrock
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.11214.1056
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/ablwE9eTT6KMhu2L7xgG/Jayrock.DLL
----------------------------------------
Fleck2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/ablwE9eTT6KMhu2L7xgG/Fleck2.DLL
----------------------------------------
DomainPublicSuffix
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/ablwE9eTT6KMhu2L7xgG/DomainPublicSuffix.DLL
----------------------------------------
Jayrock.Json
    Assembly Version: 0.9.12915.0
    Win32 Version: 0.9.13422.2206
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/ablwE9eTT6KMhu2L7xgG/Jayrock.Json.DLL
----------------------------------------
KPEntryTemplates
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.0.0
    CodeBase: file:///C:/Users/[user folder]/AppData/Local/KeePass/PluginCache/vSG3OytoHNNKlKob9kWs/KPEntryTemplates.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.53.1.20815
    Win32 Version: 2.53.1.20815
    CodeBase: file:///C:/prg/off/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
