### ISSUE TITLE
KeeAnywhere 1.5.1 doesn't work with KeePass 2.43

### ISSUE THREAD

**Issue by VivantSenior** [Kyrodan/KeeAnywhere#184]
```
Operation is not valid due to the current state of the object.
KeePass
	at KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginlnfo plgx, String strBuildPre, String strBuildPost)
	at KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginlnfo plgx, IStatusLogger slStatus)
	at KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
	at KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
	System.String Compile(System.String, KeePass.Plugins.PlgxPluginlnfo, System.String, System.String)
```

**Comment by PaceyIV** [comment]
In my case the error is different. The plug-in is unable to load the assembly KeePass.

![image](https://user-images.githubusercontent.com/5221668/67511910-19cf7900-f698-11e9-8831-563467918c98.png)

**Comment by PaceyIV** [comment]
I've download the source code, change the KeePass.exe and KeePass.XmlSerializers.dll and just recompile the solution and now works fine. Can you upgrade the release file?

**Comment by Kyrodan** [comment]
Update dependencies to KeePass 2.43.
