### ISSUE TITLE
Setting up Google drive crashes, but file with spaces no where to be found

### ISSUE THREAD

**Issue by Jewest** [Kyrodan/KeeAnywhere#325]
The crash log:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Invalid char in path 'Routebeschrijving naar Strada San Michele 50 	  47893 	Cailungo' at position 45: 9 (decimal)
   at KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   at KeeAnywhere.CloudPath.GetExtension(String path)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.50.0.20886
    Win32 Version: 2.50.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
KeeAgent
    Assembly Version: 0.12.1.0
    Win32 Version: 0.12.1.0
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/HIYK3bF73EfK3PkJiai9/KeeAgent.dll
----------------------------------------
SshAgentLib
    Assembly Version: 0.9.4.0
    Win32 Version: 0.9.4.0
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/HIYK3bF73EfK3PkJiai9/SshAgentLib.DLL
----------------------------------------
SshAgentLib.WinForms
    Assembly Version: 0.9.2.0
    Win32 Version: 0.9.2.0
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/HIYK3bF73EfK3PkJiai9/SshAgentLib.WinForms.DLL
----------------------------------------
KeeAnywhere
    Assembly Version: 2.0.3.0
    Win32 Version: 2.0.3.0
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/sv4ZVDHJdX0ifNT0mSwB/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/sv4ZVDHJdX0ifNT0mSwB/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/sv4ZVDHJdX0ifNT0mSwB/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.24.0.0
    Win32 Version: 1.24.0.0
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/sv4ZVDHJdX0ifNT0mSwB/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.50.0.20886
    Win32 Version: 2.50.0.20886
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.49.0.2201
    Win32 Version: 1.49.0.2201
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/sv4ZVDHJdX0ifNT0mSwB/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/sv4ZVDHJdX0ifNT0mSwB/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/sv4ZVDHJdX0ifNT0mSwB/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/jewe.INTRA/AppData/Local/KeePass/PluginCache/sv4ZVDHJdX0ifNT0mSwB/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Jewest** [comment]
Version is the lastest and greatest, was working on my previous pc.
The text "Routebeschrijving naar Strada San Michele 50 	  47893 	Cailungo", is something from the google maps and not drive.
How can I work around the problem?
I assume that the plugin is trying to get all the files from the drive, inorder for me to select one.
Can I hack the file path somewhere?
