### ISSUE TITLE
Unhandled Exception - Google Cloud Drive

### ISSUE THREAD

**Issue by kmquackenbush** [Kyrodan/KeeAnywhere#346]
When selecting "Open from Cloud Drive" I see an Unhandled Exception error. This error occurs for select users on the PC but other users who login to this PC are able to use the plugin. 

"System.ArgumentException: Invalid char in path 'GMAIL LOGON ISSUES"
![1](https://user-images.githubusercontent.com/108540575/176931306-0dedcfd3-43dc-4e96-a48a-c3febf30a412.PNG)

-Deleted local account from PC
-Uninstalled/Reinstalled KeePass/KeeAnywhere

**Comment by kmquackenbush** [comment]
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Invalid char in path 'GMAIL LOGON ISSUES	' at position 18: 9 (decimal)
   at KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   at KeeAnywhere.CloudPath.GetExtension(String path)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.51.1.15884
    Win32 Version: 2.51.1.0
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 2.0.3.0
    Win32 Version: 2.0.3.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Assembly Version: 1.24.0.0
    Win32 Version: 1.24.0.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Graph.Core.DLL
----------------------------------------
IdentityModel.OidcClient
    Assembly Version: 3.0.0.0
    Win32 Version: 3.1.2.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/IdentityModel.OidcClient.DLL
----------------------------------------
Box.V2
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Box.V2.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.Core.DLL
----------------------------------------
CredentialManagement
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/CredentialManagement.DLL
----------------------------------------
IdentityModel
    Assembly Version: 4.1.0.0
    Win32 Version: 4.1.0.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/IdentityModel.DLL
----------------------------------------
AWSSDK.Core
    Assembly Version: 3.3.0.0
    Win32 Version: 3.5.2.5
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/AWSSDK.Core.DLL
----------------------------------------
AWSSDK.S3
    Assembly Version: 3.3.0.0
    Win32 Version: 3.5.8.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/AWSSDK.S3.DLL
----------------------------------------
Microsoft.Azure.Storage.Common
    Assembly Version: 11.2.2.0
    Win32 Version: 11.2.2.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Azure.Storage.Common.DLL
----------------------------------------
Microsoft.Azure.Storage.Blob
    Assembly Version: 11.2.2.0
    Win32 Version: 11.2.2
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Azure.Storage.Blob.DLL
----------------------------------------
Microsoft.Azure.Storage.File
    Assembly Version: 11.2.2.0
    Win32 Version: 11.2.2
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Azure.Storage.File.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Dropbox.Api
    Assembly Version: 6.6.0.0
    Win32 Version: 6.6.0.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Dropbox.Api.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.49.0.2201
    Win32 Version: 1.49.0.2201
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.49.0.0
    Win32 Version: 1.49.0.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.DLL
----------------------------------------
Kyrodan.HiDrive
    Assembly Version: 0.2.0.0
    Win32 Version: 0.2.0.43
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Kyrodan.HiDrive.DLL
----------------------------------------
Microsoft.Graph
    Assembly Version: 3.24.0.0
    Win32 Version: 3.24.0.0
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Graph.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.51.1.15884
    Win32 Version: 2.51.1.15884
    CodeBase: file:///C:/Program%20Files/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.18136
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Extensions.Logging.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.18136
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.18136
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Extensions.Options.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/System.Text.Encodings.Web.DLL
----------------------------------------
System.IdentityModel.Tokens.Jwt
    Assembly Version: 5.6.0.0
    Win32 Version: 5.6.0.61018
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/System.IdentityModel.Tokens.Jwt.DLL
----------------------------------------
Microsoft.IdentityModel.Tokens
    Assembly Version: 5.6.0.0
    Win32 Version: 5.6.0.61018
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.IdentityModel.Tokens.DLL
----------------------------------------
Microsoft.IdentityModel.Logging
    Assembly Version: 5.6.0.0
    Win32 Version: 5.6.0.61018
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.IdentityModel.Logging.DLL
----------------------------------------
Microsoft.IdentityModel.JsonWebTokens
    Assembly Version: 5.6.0.0
    Win32 Version: 5.6.0.61018
    CodeBase: file:///C:/Users/pacuna/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.IdentityModel.JsonWebTokens.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

`

**Comment by micceo** [comment]
Hi!

In the same situation. A new install and KeeAnywhere plugin added. Exception trying to Open Cloud Drive. Added Google Drive successfully under settings, no problem there.  
Windows 11, Swedish locale.

Here is the exception generated when trying open File/Open/Cloud Drive.

`Information om att aktivera JIT-felsökning i stället för den 
här dialogrutan finns i slutet av det här meddelandet.

************** Undantagstext **************
System.ArgumentException: Invalid char in path 'Kopia av Namnlöst formulär
' at position 26: 10 (decimal)
   vid KeeAnywhere.CloudPath.CheckInvalidPathChars(String path)
   vid KeeAnywhere.CloudPath.GetExtension(String path)
   vid KeeAnywhere.Forms.CloudDriveFilePicker.<UpdateListView>d__15.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid KeeAnywhere.Forms.CloudDriveFilePicker.<SetSelectedItem>d__12.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid KeeAnywhere.Forms.CloudDriveFilePicker.<SetProvider>d__19.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid KeeAnywhere.Forms.CloudDriveFilePicker.<OnAccountChanged>d__c.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Inlästa sammansättningar **************
mscorlib
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Sammansättningsversion: 2.51.1.15884
    Win32-version: 2.51.1.0
    CodeBase: file:///C:/prg/off/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
KeeAnywhere
    Sammansättningsversion: 2.0.3.0
    Win32-version: 2.0.3.0
    CodeBase: file:///C:/Users/user01/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Sammansättningsversion: 4.2.29.0
    Win32-version: 4.2.29.0
    CodeBase: file:///C:/Users/user01/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Sammansättningsversion: 12.0.0.0
    Win32-version: 12.0.3.23909
    CodeBase: file:///C:/Users/user01/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.Graph.Core
    Sammansättningsversion: 1.24.0.0
    Win32-version: 1.24.0.0
    CodeBase: file:///C:/Users/user01/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Microsoft.Graph.Core.DLL
----------------------------------------
System.Numerics
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Security
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
KeePass.XmlSerializers
    Sammansättningsversion: 2.51.1.15884
    Win32-version: 2.51.1.15884
    CodeBase: file:///C:/prg/off/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
mscorlib.resources
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_sv_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Google.Apis.Drive.v3
    Sammansättningsversion: 1.49.0.2201
    Win32-version: 1.49.0.2201
    CodeBase: file:///C:/Users/user01/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Sammansättningsversion: 1.49.0.0
    Win32-version: 1.49.0.0
    CodeBase: file:///C:/Users/user01/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Sammansättningsversion: 1.49.0.0
    Win32-version: 1.49.0.0
    CodeBase: file:///C:/Users/user01/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Sammansättningsversion: 1.49.0.0
    Win32-version: 1.49.0.0
    CodeBase: file:///C:/Users/user01/AppData/Local/KeePass/PluginCache/BUmEy1qsx7UOmgBBtGif/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Sammansättningsversion: 4.0.0.0
    Win32-version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT-felsökning **************
För att aktivera JIT-felsökning (just-in-time ) måste .config-filen för det här
tillämpningsprogrammet eller datorn (machine.config) ha 
jitDebugging-värdet angivet i avsnittet system.windows.forms.
Tillämpningsprogrammet måste också vara kompilerat med felsökning
aktiverat.

Till exempel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

När JIT-felsökning är aktiverad kommer alla undantag som inte hanteras
att skickas till JIT-felsökningsprogrammet som är registrerat på datorn
snarare än att hanteras av den här dialogrutan.


`

**Comment by micceo** [comment]
Hi again! Workaround but just to get it to open my file.
Copied %appdata% settings over to the new machine and got it to open the gdrive: file. But can still not use Open Cloud drive.
Had to reauthenticate Google Drive (remove and add it again) but after that it worked.
