### ISSUE TITLE
Unhandled exception adding Google Drive account

### ISSUE THREAD

**Issue by PeterEeg** [Kyrodan/KeeAnywhere#48]
I get the following unhandled exception after selecting "Allow" in the google drive authorization view in the browser (Chrome).
If I choose continue, no account has been registeret in KeePass.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.StorageProviders.GoogleDrive.GoogleDriveHelper.<GetClient>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.StorageProviders.GoogleDrive.GoogleDriveStorageConfigurator.<CreateAccount>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.StorageProviders.StorageService.<CreateAccount>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.UIService.<CreateOrUpdateAccount>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.Forms.SettingsForm.<OnAccountAdd>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
KeePass
    Assembly Version: 2.34.0.15991
    Win32 Version: 2.34.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
KeeAnywhere
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/KeeAnywhere.dll
----------------------------------------
System.Net.Http.Primitives
    Assembly Version: 4.2.29.0
    Win32 Version: 4.2.29.0
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/System.Net.Http.Primitives.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.3.19514
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/Newtonsoft.Json.DLL
----------------------------------------
CredentialManagement
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/CredentialManagement.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
KeePass.XmlSerializers
    Assembly Version: 2.34.0.15991
    Win32 Version: 2.34.0.15991
    CodeBase: file:///C:/Program%20Files%20(x86)/KeePass%20Password%20Safe%202/KeePass.XmlSerializers.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.10.1.427
    Win32 Version: 1.10.1.427
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.10.0.25332
    Win32 Version: 1.10.0.25332
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/Google.Apis.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.10.0.25331
    Win32 Version: 1.10.0.25331
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/Google.Apis.Core.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.10.0.25333
    Win32 Version: 1.10.0.25333
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/Google.Apis.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
Microsoft.Threading.Tasks
    Assembly Version: 1.0.12.0
    Win32 Version: 1.0.168.0
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/Microsoft.Threading.Tasks.DLL
----------------------------------------
Google.Apis.Auth.PlatformServices
    Assembly Version: 1.10.0.25333
    Win32 Version: 1.10.0.25333
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/Google.Apis.Auth.PlatformServices.DLL
----------------------------------------
Google.Apis.PlatformServices
    Assembly Version: 1.10.0.25332
    Win32 Version: 1.10.0.25332
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/Google.Apis.PlatformServices.DLL
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Primitives/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Primitives.dll
----------------------------------------
Microsoft.Threading.Tasks.Extensions.Desktop
    Assembly Version: 1.0.168.0
    Win32 Version: 1.0.168.0
    CodeBase: file:///C:/Users/eegp/AppData/Local/KeePass/PluginCache/pNWmTp3vZ2KNYj6vkecv/Microsoft.Threading.Tasks.Extensions.Desktop.DLL
----------------------------------------
System.Net
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by PeterEeg** [comment]
It seems to be an issue with my corporate windows 7 machine, you probably shouldn't pay any attention to this issue.
