### ISSUE TITLE
OneDrive: Microsoft.Graph.ServiceException

### ISSUE THREAD

**Issue by sekogan** [Kyrodan/KeeAnywhere#77]
OneDrive authorization doesn't work anymore after I've changed password on my Microsoft account.

Steps to reproduce the issue:
- Add a OneDrive account to KeeAnywhere Settings.
- Change password of your Microsoft account on microsoft.com.
- Remove the OneDrive account from KeeAnywhere Settings and try to add it again. In the popup window enter email, password, approve 2-factor authentication request on your phone, press Yes on the "Let this app access your info?" page.

Expected:
- The account is added to the list.

Actual:
- A message box is displayed:

```
---------------------------
KeePass - Fatal Error
---------------------------
A fatal error has occurred!
An extended error report has been copied to the clipboard.
Authentication failed!
Exception of type 'Microsoft.Graph.ServiceException' was thrown.
---------------------------
OK   
---------------------------
```

Clipboard content:
```
Authentication failed!

Exception of type 'Microsoft.Graph.ServiceException' was thrown.
Microsoft.Graph.Core
   at Microsoft.Graph.HttpProvider.<SendRequestAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.OneDrive.Sdk.Authentication.OAuthHelper.<SendTokenRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.StorageProviders.OneDrive.OneDriveStorageConfigurator.<Claim>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KeeAnywhere.OAuth2.OAuth2Form.<OnNavigated>d__3.MoveNext()
Void MoveNext()


Inner:
An error occurred while sending the request.
mscorlib
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.HttpProvider.<SendRequestAsync>d__21.MoveNext()
Void ThrowForNonSuccess(System.Threading.Tasks.Task)
```

KeeAnywhere.Accounts.json contains an empty array:
```
[]
```

KeePass 2.35
KeeAnywhere 1.3.1.0
Windows 10 RS1 x64

**Comment by Kyrodan** [comment]
That is weird. Could you please go to https://account.live.com/consent/Manage and remove KeeAnywhere from there. After that please try to re-add your OneDrive account in KeeAnywhere.

**Comment by Kyrodan** [comment]
That is weird. Could you please go to https://account.live.com/consent/Manage and remove KeeAnywhere from there. After that please try to re-add your OneDrive account in KeeAnywhere.

**Comment by Kyrodan** [comment]
Closing due to inactivity.
In Version 1.4.0 an updated library for OneDrive will be used, so maybe this also fixes this problem.

**Comment by RegSerg** [comment]
I have the same issue. But as I  is new user of your plugins, I had this issue on create account step. My Onedrive account has 2-factor authentication.  I use 1.3.1 version. I try to use KeeAnywhere-1.4.0-unstable.plgx with the same result.

Text of error:
=======================================
Authentication failed!

Выдано исключение типа "Microsoft.Graph.ServiceException".
Microsoft.Graph.Core
   в Microsoft.Graph.HttpProvider.<SendRequestAsync>d__21.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.OneDrive.Sdk.Authentication.OAuthHelper.<SendTokenRequestAsync>d__12.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.OneDrive.Sdk.Authentication.OAuthHelper.<RedeemAuthorizationCodeAsync>d__6.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в KeeAnywhere.StorageProviders.OneDrive.OneDriveStorageConfigurator.<Claim>d__b.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в KeeAnywhere.OAuth2.OAuth2Form.<OnNavigated>d__3.MoveNext()
Void MoveNext()


Inner:
Произошла ошибка при отправке запроса.
mscorlib
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.Graph.HttpProvider.<SendRequestAsync>d__21.MoveNext()
Void ThrowForNonSuccess(System.Threading.Tasks.Task)

**Comment by Kyrodan** [comment]
Hi @RegSerg ,

could you please try this new unstable build:
[KeeAnywhere-1.4.0-unstable.plgx.zip](https://github.com/Kyrodan/KeeAnywhere/files/1038479/KeeAnywhere-1.4.0-unstable.plgx.zip)

If it does not work: do use a proxy?

Regards,
Daniel

**Comment by RegSerg** [comment]
Hi,
With this version of KeeAnywhere-1.4.0-unstable.plgx all works.
Thanks
Sergey
